### ISSUE TITLE
Project Wireframes (Mock-up)

### ISSUE THREAD

**Issue by EkaterinaSerga** [team-i-grace-shopper/shop-x#8]
- [x] Landing Home page (make sure to have nav with Login & Sign-up choice)
- [x] All products view
- [x] Cart
- [x] Login view
- [x] Signup view
- [x] Order confirmation page

**Comment by EkaterinaSerga** [comment]
Love it!

**Comment by filafb** [comment]
Is this task done? Can we close it?

**Comment by treaganbirbal** [comment]
![image](https://user-images.githubusercontent.com/43793458/85044730-0b205f80-b15c-11ea-84a0-5c473df4c0a9.png)

**Comment by courtedwar1** [comment]
I will update the wireframes folder to include this image instead of what we currently have. Look out for a pull request to close this.
