### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by EkaterinaSerga** [team-i-grace-shopper/shop-x#9]
- [x] User model
- [x] Product model (make sure to have: category field)
- [x] Order model

belongs to #43

**Comment by PolymathWanderer** [comment]
![DatabaseDiagram(1)](https://user-images.githubusercontent.com/46685118/84817562-2c117500-afe3-11ea-87e5-434ffaf9c085.png)

**Comment by courtedwar1** [comment]
For the order model, I would suggest adding a field for order total (of decimal/float type) and items in order (of array type) — thinking ahead to serving up order histories.

For the product model, maybe we should update the price field to be of decimal/float type?

**Comment by treaganbirbal** [comment]
Task for schema: 
Total Price
Status to determine if purchased or still in cart
Quantity

**Comment by PolymathWanderer** [comment]
Just updated my previous comment to what was requested.

**Comment by courtedwar1** [comment]
How do we all feel about this?

![shopX-dbModels](https://user-images.githubusercontent.com/56009837/85175518-a2adad00-b245-11ea-8799-e647e5bd6d05.jpeg)
